use-workspace-deps = true
static = ["samling-clorinde/LICENSE"]

[package]
name = "samling-clorinde"
version = "0.12.0"
edition = "2021"
license = "MIT"
publish = true
description = "Database queries etc for the `samling` crate"
repository = "https://github.com/jacobsvante/samling"
documentation = "https://docs.rs/samling/"
homepage = "https://github.com/jacobsvante/samling"
